### ISSUE TITLE
How to understand "confidence" of Baidu API

### ISSUE THREAD

**Issue by yafeiguo** [caijun/geoChina#8]
How to understand the confidence number in output when using baidu api?

**Comment by yafeiguo** [comment]
"confidence=80"means that the lat/lng output's reliability is about 80%. Right? Bigger confidence number represents higher reliability? Then, what is the meaning of "confidence=0"? Thanks in advance.

**Comment by yafeiguo** [comment]
![image](https://user-images.githubusercontent.com/25188705/26990983-b1e1a60a-4d26-11e7-844f-a8b44fda9992.png)
Here is the table of baidu geocoding results.
http://developer.baidu.com/map/skins/MySkin/resources/iframs/webapi-geocoding.html
Is it possible to get the variable named "precise" in the table above in outputs of geoChina?

**Comment by caijun** [comment]
Your understanding of geocoding reliability is correct. Larger confidence higher reliability. Yet I haven't encountered the situation of `conf = 0`. Could you give a reproducible example? 

Currently geoChina can only return`lat`, `lng` and `conf` variables and don't return `precise` information since I prefer to call Google API to finish geocoding task. I recommend you trying Google geocoding API.
